name: Scala CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        jdk:
          - 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
          cache: sbt
      - name: Check code format with scalafmt
        run: ./sbt scalafmtCheckAll scalafmtSbtCheck
      - name: Run tests
        run: ./sbt +test
